
<div class="container-fluid py-3">
   <?php if(empty($commande)): ?> 
       <div class="d-flex justify-content-center align-items-center mt-5 py-5">
           <p class="h2 mt-4">No BOOK issue</p> 
       </div>
    <?php else: ?>

<?php foreach($commande as $values): ?>
   <table class="table table-striped table-bordered mt-4">
    <thead class="bg-info fw-bolder text-uppercase">
        <td  scope="col">avatar</td>
        <td  scope="col">nom book</td>
        <td  scope="col">author</td>
        <td  scope="col">Prix</td>
        <td  scope="col">quantity</td>
        <td  scope="col">livraison</td>
        <td  scope="col">valider</td>
</thead>
         <?php foreach($book->all_line_commande_by_id($values['idcommande']) as $items): ?>
         
    <tr>
     <td>
      <img width='50px' src="<?=$items['avatar']?>" alt=<?=$items['name_book'];?>>
    </td>
    <td>
        <?=$items['name_book'];?>
    </td>
    <td>
    <?=$items['author_book'];?>
    </td>
    <td>
    <?=$items['Prix'] *$items['quantity'];?> Dt
    </td>
    <td>
        <?=$items['quantity']?>
    </td>
    <td>
        <?=$items['aveclivraison']==1 ? 'avec livraison' : 'sans livraison'?>
    </td>
    <td>  
        <?=$items['valider']==0 ? 'not yet <div class=" spinner-border text-dark" role="status"> </div>'
                                  :'<i class="text-success mx-4 fa-solid fa-check"></i>'?>
    </td>
    </tr>
     <?php  endforeach; ?>
     </table>
    <?php endforeach;?>   
 
<?php endif; ?>
</div>