 <h1 class="text-center pt-3">List Of comments :</h1>
<div class="row d-flex justify-content-center p-5">
 <?php foreach($comments as $com) :?>  
   <div class="col-lg-4 py-4 mx-5">
   <div class="card shadow">
         <div style="font-size:25px" class="card-header text-center fw-bolder">
                <?=$com['nom']?>
         </div>
        <div class="card-body mb-2">
                <span style="font-size:20px" class="text-primary fw-bolder mb-2" >email: </span><?=$com['email'];?> 
                <p style="font-size:20px" class="text-primary pt-2">Description :</p>
                  <?=$com['messages']?>
        </div>
     </div>

</div>
<?php endforeach;?>
</div>
</div>