
<style>
.reglage_card{
   transition-duration: 0.4s;
   cursor:pointer;
 }

 .reglage_card:hover{
    transform: scale(150px);
    box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2),0 6px 20px 0 rgba(0,0,0,0.19);
 }
</style>

<div>
    <h1 style="z-index:1;margin-left:690px;margin-top:15px">List Of Books :</h1>
<?php if(empty($books)): ?>
        no books 
 <?php endif;?>
<div class="row" style="margin-left:290px">
 <?php foreach($books as $book) :?>  
   <div class="col-lg-4 mt-5">
        <div class="card mx-1 reglage_card" style="width:18rem;">
            <img src="<?= $book['avatar'] ?>" height="200px" class="card-img-top" alt="photo book">
             <div class="card-body">
                <h5 class="card-title">name   :<?=$book['name_book'];?></h5>
                 <h5 class="card-title">author :<?=$book['author_book'];?></h5>
                 decription : <p class="card-text"><?=$book['description_book'];?></p>
                  Status :<span style="color:<?= $book['status']=='enable'? 'green' :''?>" ><?= $book['status'] ;?></span>
             </div>
              <button class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">>Delete</button>
        </div>
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel.<?=$book['idbook'];?>" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel.<?=$book['idbook'];?>">Delete Book :</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
          Do you want delete <?=$book['name_book'];?> ?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-danger">Delete</button>
      </div>
    </div>
  </div>
</div>
</div>
<?php endforeach;?>
</div>
</div>