<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <?php if(empty($_SESSION) && !$show ): ?>
    <title>Accueil</title> 
    <link rel="stylesheet" href="./css/style.css">
  <?php else:?>
    <link rel="stylesheet" href="../css/style.css">
    <title><?=$page_titel?></title> 
    <?php endif;?>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

</head>
<body>

<?php if(!isset($_SESSION['name']) && !$show): ?>
<header id="accueil">
      <nav class="navbar navbar-expand-lg text-center text-uppercase fixed-top">
            <div class="container mt-4">
                <a class="navbar-brand" href="#page-top">Our Library</a>
                <button class="navbar-toggler text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fa-solid fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        <li style="--clr:#00ade1" class="nav-item mx-4 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-5 rounded" href="#accueil" data-text="&nbsp;Accueil">Accueil</a></li>
                        <li id="seconde" style="--clr:#ff6493" class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-5 rounded" href="#service" data-text="&nbsp;Service">Service</a></li>
                        <li style="--clr:#ff6535" class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-5 rounded" href="#pupular_books" data-text="&nbsp;Popular_books">Popular_Books</a></li>
                        <li style="--clr:#ff6535" class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-5 rounded" href="#team" data-text="&nbsp;profil">profil</a></li>
                        <li style="--clr:#ff6535" class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-5 rounded" href="#contact_us" data-text="&nbsp;Contact">Contact</a></li>
                      </ul>
                </div> 
          </div>
      </nav>
  <div class="card card_profe shadow">
    <div class="card-body">
      <h5 class="card-title text-center mb-2">Welcome <img src="./images/hello.png" width="40px" height="40px"/> </h5>
      <h6 class="card-subtitle mb-2 text-muted text-center"> To Our Amazign Library <i class="fa-solid fa-book"></i> </h6>
        <p class="card-text text-center py-2">Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus accusantium doloribus cupiditate amet laudantium maiores ab tempore magnam exercitationem aperiam.</p>
        <div class="mt-4 mb-2 text-center">
            <a href="login"   class="card-link text-secondary text-center mx-4 btn btn-outline-primary  ">Sign In</a>
            <a href="signup"  class="card-link text-center mx-5 btn btn-outline-secondary text-secondary">Sign Up</a>
        </div>
      </div>
 </div>
  <div class="more">
      <a href="#service"><button class="btn btn-warning text-light p-3 m-3 fw-bolder">Tell Me More</button></a>
  </div>
</header>  

<section>
   <article id="service" class="service py-5">
            <div class="container py-5">
                <div class="text-center py-3">
                    <h2 class=" text-uppercase">Services</h2>  
                   <div class="divider-custom">
                   	   <div class="divider-custom-line"></div>
                    	 <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                    	 <div class="divider-custom-line"></div>
               	   </div>
                </div>
                <div class="row text-center py-5">
                    <div class="col-md-4">
                        <span class="fa-stack fa-4x">
                            <i class="fas fa-circle fa-stack-2x text-warning"></i>
                            <i class="fas fa-book-bookmark fa-stack-1x text-dark "></i>
                        </span>
                        <h4 class="my-3">New Book</h4>
                        <p class="text-muted">always we have exclusive books </p>
                    </div>
                    <div class="col-md-4">
                        <span class="fa-stack fa-4x">
                            <i class="fas fa-circle fa-stack-2x text-warning"></i>
                            <i class="fas fa-sack-dollar fa-stack-1x text-dark "></i>
                        </span>
                        <h4 class="my-3">Buy Book</h4>
                        <p class="text-muted">Book prices are low in our library</p>
                    </div>
                     <div class="col-md-4">
                        <span class="fa-stack fa-4x">
                            <i class="fas fa-circle fa-stack-2x text-warning"></i>
                            <i class="fas fa-hand-holding-hand fa-stack-1x text-dark "></i>
                        </span>
                        <h4 class="my-3">Borrow Books</h4>
                        <p class="text-muted">You can borrow any book you like</p>
                    </div>
                </div>
            </div>
   </article>

    <article class="popular py-4" id="pupular_books">
    <div class="container py-5">
                <div class="text-center py-5">
                    <h2 class="section-heading text-uppercase">Top 3 Popular Books</h2>
                    <div class="divider-custom">
                   	   <div class="divider-custom-line" ></div>
                    	 <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                    	 <div class="divider-custom-line"></div>
               	   </div>
                </div>
                <?php require "./gettopbook/index.php" ?> 
     </div>       
    </article>

    <article id="team" class="py-5">
        <div class="container py-5">
                <div class="text-center py-4">
                    <h2 class="section-heading text-uppercase">U wanna know us</h2>
                    <h3 class="section-subheading text-muted">Front-End Developer</h3>
                    <div class="divider-custom">
                   	   <div class="divider-custom-line" ></div>
                    	 <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                    	 <div class="divider-custom-line"></div>
               	   </div>
                  </div>
                <div class="row ">
                    <div class="col-lg-12 text-center py-3">
                            <img class="mx-auto rounded-circle" src="storage/personnel/dev.jpg" alt="..." />
                            <h4>Talel Mejri</h4>
                            <p class="text-muted">Fllow Me.</p>
                              <a class="btn btn-dark  mx-2" href="#!"><i class="fa-brands fa-youtube"></i></a>
                              <a class="btn btn-dark  mx-2" href="#!"><i class="fab fa-twitter"></i></a>
                              <a class="btn btn-dark  mx-2" href="#!" ><i class="fab fa-facebook-f"></i></a>
                              <a class="btn btn-dark  mx-2" href="#!" ><i class="fab fa-linkedin-in"></i></a>
                   </div>
                </div>
       </div>
    </article>

  <article id="contact_us" class="contact py-5">
    <div class="container py-5">
                <div class="text-center py-4">
                    <h2 class=" text-uppercase">Contact Us</h2>
                    <div class="divider-custom">
                   	   <div class="divider-custom-line" ></div>
                    	 <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                    	 <div class="divider-custom-line"></div>
               	   </div>
                </div>
             <form action="./comment.php" method="post" class="shadow p-4 m-3 rounded">
              <h4 class="fw-bolder text-primary">Get In Touch</h4>
              <p class="text-muted-primary">we are here for you ! how can we help ?</p>
             <div class="row">
               <div class="col-lg-6">
              <div class="mb-3">
                <input  type="name" name="name" class="form-control shadow" placeholder="Entre your name" <?= array_key_exists('name',$errors) ? 'is-invalid' :''; ?> >
                <small class="text-danger"><?= array_key_exists('name',$errors) ? $errors['name'] :''; ?></small>
              </div>
              <div class="mb-3">
            
                  <input type="email" name="email" placeholder="Entrer your email address" class="shadow form-control shadow" id="exampleInputEmail1" aria-describedby="emailHelp"  <?= array_key_exists('email',$errors) ? 'is-invalid' :'';?>>
                  <small class="text-danger"><?= array_key_exists('email',$errors) ? $errors['email'] :''; ?></small>
              </div>
              <div class="mb-3">
              <textarea placeholder="Go ahead , we are listening" class="shadow rounded" style="outline:none;border:none;padding:10px" name="messages" cols="20"  rows="10" <?= array_key_exists('message',$errors) ? 'is-invalid' :'';?> ></textarea>
              <small class="text-danger"><?= array_key_exists('message',$errors) ? $errors['message'] :''; ?></small>  
            </div>
                <button style="width:100%" name="submit" type="submit" class="mb-4 btn btn-outline-primary">Send</button>
                </div>  
                <div class="col-sm-6 text-center">
                      <div class="row text-center">
                        <div class="col-md-12 text-center mb-5">
                          <img id="image_contact" src="./images/leisure _ relax, chill, sitting, drink, beverage, home, armchair, furniture, plant, decoration@2x.png" alt="">
                        </div>
                        <div class="col-md-12 ">
                             <div class="row mb-3 ">
                                 <div class="col-md-2 ">
                                 <span class="fa-stack fa-1x">
                                   <i class="fas fa-circle fa-stack-2x text-primary"></i>
                                   <i class="fas fa-location-dot fa-stack-1x text-white "></i>
                                </span>
                                </div>
                                <div class="col-md-2 ">
                                      Bahra
                                </div>
                            </div>
                            <div class="row mb-3 ">
                                 <div class="col-md-2 ">
                                 <span class="fa-stack fa-1x">
                                   <i class="fas fa-circle fa-stack-2x text-primary"></i>
                                   <i class="fas fa-phone fa-stack-1x text-white "></i>
                                </span>
                                </div>
                                <div class="col-md-2 ">
                                      +21629036027
                                </div>
                            </div>
                            <div class="row ">
                                 <div class="col-md-2 ">
                                 <span class="fa-stack fa-1x">
                                   <i class="fas fa-circle fa-stack-2x text-primary"></i>
                                   <i class="fas fa-envelope fa-stack-1x text-white "></i>
                                </span>
                                </div>
                                <div class="col-md-2 ">
                                      talelmejri8@gmail.com
                                </div>
                            </div>
                        </div>
                    </div>
                    </div>  
                </div>
              </div>  
              </form>
          </div>
    </article>

</section>

<footer>

     <div class="container-fluid py-3 bg-secondary">
        <div class="row text-center">
           <div class="col-md-4 text-white">Copyright &copy; Library lbeez 2022</div>
           <div class="col-md-4">
              <a class="btn btn-warning text-white mx-2" href="#!" aria-label="Twitter"><i class="fab fa-twitter"></i></a>
              <a class="btn btn-warning text-white mx-2" href="#!" aria-label="Facebook"><i class="fab fa-facebook-f"></i></a>
              <a class="btn  btn-warning text-white mx-2" href="#!" aria-label="LinkedIn"><i class="fab fa-linkedin-in"></i></a>
           </div>
           <div class="col-md-4"> 
              <a class="text-white text-decoration-none me-3" href="#">Privacy Policy</a>
              <a class="text-white text-decoration-none" href="#">Terms of Use</a>
           </div>
        </div>
     </div>
</footer>

<?php endif;
    ?>
<?php if(isset($_SESSION['name']) && !$show): ?>

     <div class="sidebar fixed-top" id="sidebar">
        <div class="py-4 mx-3">
           <div class="mosule d-flex alig-items-center">
                <img src="<?=$_SESSION['avatar_admin'];?>" width="100" height="80" class="rounded-circle img-thumbnail shadow-sm" alt="">
              <div class="body py-3 px-2">
                 <p class="m-0"><?=$_SESSION['name'];?></p>
                 <p class="font-weight-normal text-muted">Front End</p>
              </div>
          </div>
       </div>

        
 
    <span class="fs-5 fw-semibold px-5 ">Dashboard</span>
    </a>

    <ul class="list-unstyled flex-column ps-0 mx-4 mt-4">

      <li class="mb-3">
        <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#home-collapse" aria-expanded="true">
          Home
        </button>
        <div class="collapse show" id="home-collapse">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><a href="../profiladmin" class="link-dark rounded">Overview <i class="fa-solid fa-chart-line px-2"></i></a></li>
            <li><a href="../allcomment" class="link-dark rounded">Comments <i class="fa-solid fa-comment px-2"></i></a></li>
          </ul>
        </div>
      </li>

      <li class="mb-3">
        <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#dashboard-collapse" aria-expanded="false">
          Books Manager
        </button>
        <div class="collapse" id="dashboard-collapse">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><a href="../addbook" class="link-dark rounded">Add Book <i class="fa-solid fa-plus px-2"></i></a></li>
            <li><a href="../consultebook" class="link-dark rounded">Consulte Book <i class="fa-solid fa-clipboard-list px-2"></i></i></a></li>
          </ul>
        </div>
      </li>

      <li class="mb-3">
        <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#dashboard-collapsee" aria-expanded="false">
          User Manager
        </button>
        <div class="collapse" id="dashboard-collapsee">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><a href="../alluser" class="link-dark rounded">Consulte User <i class="fa-solid fa-clipboard-list px-2"></i></a></li>
            <li><a href="../listuserdeleted" class="link-dark rounded">Consulte user deleted<i class="fa-solid fa-ban px-1"></i> </a></li>
            <li><a href="#" class="link-dark rounded">Chat with Our user <i class="fa-solid fa-comments px-2"></i> </a></li>
          </ul>
        </div>
      </li>

      <li class="mb-5">
        <button class="btn mx-4 align-items-center rounded ">
          <a class="text-decoration-none text-dark font-weight-bold" href=""> Books Issue <i class="fa-solid fa-id-card-clip px-2"></i></a>
        </button>
      </li>
      <div class="py-5 mt-5 px-5">
          <a class="text-decoration-none text-dark font-weight-bold" href="../log_out.php">Log Out <i class="fa-solid fa-right-from-bracket px-2"></i></a>
      </div>
    </div>

</div>

    <div class="page-content " id="content">
         <div class="bg-secondary p-3">
            <button class="btn btn-outline-dark mx-1"  id="btn1"><i class="fa-solid fa-list"></i></button>
            <a class="float-end" href="../editadmin">
                <span class="fa-stack fa-1x ">
                       <i class="fas fa-circle fa-stack-2x text-primary"></i>
                       <i class="fas fa-user-gear fa-stack-1x text-white"></i>
                </span>
            </a>
        </div>
        
        <?php include $template.".phtml"; ?>
        <!-- <p >a9wa chlendi ;)</p>-->
    </div>
    <?php endif;?>
     <!--for login and sign up-->
     <?php if($show): ?>
      <?php include $template.".phtml"; ?>
      <?php endif; ?>
</body>
<script>
  window.addEventListener("scroll", function () {
  const header = document.querySelector("nav");
  header.classList.toggle("sticky", window.scrollY > 0);
});

let btn = document.querySelector("#btn1");
let side_bar = document.querySelector("#sidebar");
let content = document.querySelector("#content");
btn.addEventListener("click", function () {
  side_bar.classList.toggle("active");
  content.classList.toggle("active");
});

</script>
<script src="../js/script.js"></script>
<script src="https://kit.fontawesome.com/c5bebe1cfa.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</html>