
<form action="<?=$_SERVER['PHP_SELF'] ?>" method="POST">
<?php if(array_key_exists('type',$_GET)): ?>
<div class="alert alert-<?=$_GET['type']?>" role="alert">
 <?= $_GET['msg'] ?>
</div>
<?php endif;?>
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Email address</label>
    <input type="text" name="email" class="form-control" id="exampleInputEmail1">
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1"  class="form-label">Password</label>
    <input type="password" name="password" class="form-control" id="exampleInputPassword1">
  </div>
  <button type="submit" name="submit" class="btn btn-primary">Submit</button>
</form>