<section class="mt-5">
<div class="row">

  <div class="col-lg-4">
    <div class="card">
      <div class="card-body text-center bg-info">
         <strong class="mb-3">nombre of all the books</strong>
         <p class="mt-4" style="font-size:20px"><?=$number?></p>
      </div>
    </div>
  </div>

  <div class="col-lg-4">
    <div class="card">
      <div class="card-body text-center bg-primary">
         <strong class="mb-3">nombre of Books enable</strong>
         <p class="mt-4" style="font-size:20px"><?=$number?></p>
      </div>
    </div>
  </div>

  <div class="col-lg-4">
    <div class="card">
      <div class="card-body bg-warning text-center">
      <strong class="mb-3">nombre of books <br> issue</strong>
         <p class="mt-4" style="font-size:20px"><?=$number?></p>
      </div>
    </div>
  </div>
</div>
</section>