
<style>
.reglage_card{
   transition-duration: 0.4s;
 }
.active{
  background-color:blue;
}
 .reglage_card:hover{
    transform: scale(150px);
    box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2),0 6px 20px 0 rgba(0,0,0,0.19);
 }
</style>

<div class="text-center" >
    <h1 class="text-center pt-3">List Of Books :</h1>
    <form action="index.php" method="post">
          <button  class="<?= empty($books) ? 'd-none' :''?> btn btn-danger" name="delete">Delete All</button>
    </form>
<?php if(empty($books)): ?>
       <div style="font-size:20px" class="py-5 mt-5">
             No Books
       </div>  
 <?php endif;?>
 <form class="mt-4" action="index.php" method="POST">
    <div class="d-flex justify-content-center">
    <input name="search" type="search" style="width:20%" placeholder="Search by name book" class="form-control">
    <button name="btn_search" class="btn btn-success mx-2">search</button>
    </div>
 </form>
 <div class=" mt-4">
  <div class="row">
    <div class="col-md-6">
     <form action="index.php" method="GET">
        <input type="hidden" id="contenu_order" value=<?=isset($_GET['choix']) ? $_GET['choix'] : ''?>>
        <select name="choix" class="custom-select custom-select-sm form-control-sm" id="select_contenu" onchange="this.form.submit()">
            <?php foreach(['name_book'=>"Name Book","author_book"=>"Author","nbr_book"=>"Nombre Book","Prix"=>"Prix"] as $key=>$value) : ?>
                 <option value="<?=$key?>"><?=$value?></option>
            <?php endforeach; ?>
        </select>
     
     </div>
     <div class="col-md-6 ">
              <input type="hidden" id="record" value=<?=isset($_GET['show_book']) ? $_GET['show_book'] : 5?>>
             <label >Show</label>
             <select name="show_book" class="custom-select custom-select-sm form-control-sm" id="show_book" onchange="this.form.submit()">
                <?php foreach([100,10,5,2] as $value) :?>
                   <option value="<?=$value?>"><?=$value?></option>
                <?php endforeach; ?>
             </select>
             books
         </form>
     </div>
     </div>
 </div>
<div class="row d-flex justify-content-center">
<?php if(array_key_exists('type',$_GET)): ?>
      <div style="width:90%" class="mt-4 text-center alert alert-<?=$_GET['type']?>" role="alert">
           <?=$_GET['msg'];?>
      </div>
    <?php endif;?>
 <?php foreach($books as $book) :?>  
<div class="col-lg-5 py-4 mx-3 m-3">
<div class="card mb-3 reglage_card ">
  <div class="row g-0">
    <div class="col-md-5">
      <img src="<?= $book['avatar'] ?>" width="100%"  class="img-fluid rounded-start" alt="photo book">
    </div>
    <div class="col-md-7" >
        <div class="card-header bg-info fw-bolder text-white">
           <?=$book['name_book']?>
        </div>
        <div class="card-body">

             <table class="table table-danger rounded ">
                <thead>
                  <tr>
                    <td  class="fw-bolder">Author</td>
                    <td class="text-center fw-bolder">Nbr Despo</td>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td><?=$book['author_book']?></td>
                    <td class="text-center"><?=$book['nbr_book']?></td>
                  </tr>
                </tbody>
             </table>
             
             <div class="mt-2 mb-3">
               <h5 class="fw-bolder">Description :</h5>
                 <p class="text-muted"><?=$book['description_book']?></p> 
             </div>

             <div class="mt-2 mb-3">
               <h5 class="fw-bolder">Prix :</h5>
                 <p style="font-size:25px" class="text-warning"><?=$book['Prix']?> Dt</p> 
             </div>

             <div class="row py-3 mb-0">
                  <div class="col-md-6 mb-2">
                       <button class="btn btn-outline-danger text-dark" data-bs-toggle="modal" data-bs-target="#exampleModal<?=$book['idbook'];?>"><i class="fa-solid fa-trash"></i></button>
                  </div>
                  <div class="col-md-6">
                       <button class="btn btn-outline-warning"><a class="text-decoration-none  text-dark" href="../updatebook?id=<?=$book['idbook'];?>"> <i class="fa-solid fa-pen-to-square"></i> </a></button>
                  </div>
             </div>
        </div>
  </div>
 </div>
</div>

       
<div class="modal fade" id="exampleModal<?=$book['idbook'];?>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel<?=$book['idbook'];?>">Delete Book :</h5>
       <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></a>
      </div>
      <div class="modal-body">
          Do you want delete <?=$book['name_book'];?> ?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <a href="../deleteBook.php?id=<?=$book['idbook']?>"> <button type="button" class="btn btn-danger">Delete</button></a>
      </div>
    </div>
  </div>
</div>
</div>
<?php endforeach;?>

</div>

</div>
<div class="d-flex justify-content-center">
<ul class="pagination">
    <li class="page-item">
    <a class="page-link" href="index.php?<?=isset($_GET['show_book']) ? 'show_book='.$_GET['show_book'].'&' : '' ?>page=<?=$previous?>&<?=isset($_GET['choix']) ? 'choix='.$_GET['choix'] : ''?>">previous</a>
    </li>
       <?php for($i=1;$i<=$pages;$i++):
        
        if($i==$page){
          $active="active";
       }else{
        $active="";
       }?>
  
       
      <li class="page-item <?=$active?>"><a class="page-link" href="index.php?<?=isset($_GET['show_book']) ? 'show_book='.$_GET['show_book'].'&' : '' ?>page=<?=$i?>&<?=isset($_GET['choix']) ? 'choix='.$_GET['choix'] : ''?>"><?=$i?></a></li>
      <?php endfor; ?>
    <li class="page-item">
      <a class="page-link" href="index.php?<?=isset($_GET['show_book']) ? 'show_book='.$_GET['show_book'].'&' : '' ?>page=<?=$next?>&<?=isset($_GET['choix']) ? 'choix='.$_GET['choix'] : ''?>">Next</a>
    </li>
  </ul>
  </div>
<script>

 
  let hidden_contenu=document.getElementById('contenu_order').value;   
  console.log(hidden_contenu);
  let select_contenu=document.getElementById('select_contenu');
  for(let i=0;i<select_contenu.length;i++){
    if(select_contenu[i].value==hidden_contenu){
      select_contenu[i].setAttribute("selected","selected");
    }
  }   

let hidden_choix=document.getElementById('record').value;  
let choix= document.getElementById('show_book');
for(let i=0;i<choix.length;i++){
  if(choix[i].value==hidden_choix){
    choix[i].setAttribute("selected","selected");
  }
}

</script>


