<style>
input{
  height:60px;
}
img{>
  height:100%;
  width:100%;
}
.fin{
  font-size:22px;
}
</style>

<div class="login">
   <div class="d-flex justify-content-center py-3">
        <button class="text-center btn btn-outline-info d-block"><a href="/Library_project"><i class="fa-solid fa-house-user display-4"></i></a> </button>
  </div>
<div class="d-flex p-3 m-4 justify-content-center">   
    <div class="col-xl-10 col-md-12 col-lg-12 ">
          <div class="row shadow-lg rounded">
                <div class="col-lg-6 d-none d-lg-block bg-secondary">
                    <img src="../images/security _ lock, key, login, safety, protection, padlock, locked, unlock@2x.png" alt="">
                </div>
                <div class=" col-lg-6 py-5">
                      <div class="text-center">
                        <h1 class="h4 text-gray-900 mb-5">Welcome Back !</h1>
                      </div>
                    <form action="<?=$_SERVER['PHP_SELF'] ?>" method="POST">
                          <?php if(array_key_exists('type',$_GET)): ?>
                              <div class="alert alert-<?=$_GET['type']?>" role="alert">
                                 <?= $_GET['msg'] ?>
                               </div>
                          <?php endif;?>
                      <div class="mb-4">
                          <input  type="text" placeholder="Entrer Email Address..." name="email" class="form-control rounded-pill p-4" id="exampleInputEmail1">
                      </div>
                      <div class="mb-5">
                         <input type="password" placeholder="Password" name="password" class="form-control rounded-pill p-4" id="exampleInputPassword1">
                      </div>
                          <button style="font-size:19px" type="submit" name="submit" class="btn btn-primary btn-block w-100 rounded-pill">Login</button>
                      </form>
                      <hr>
                      <div class="fin text-center py-4 mb-1">
                              <a href="../forgot">Forgot Password ?</a>
                       </div>
                       <div class="fin text-center">
                              <a href="../signup">Create an Account !</a>
                      </div> 
                </div>
          </div>
    </div>
</div>
</div>