<style>
.active{
  background-color:blue;
}
</style>

<h1 class="h2 text-center py-5">List Of user </h1>
 <?php if(empty($alluser)): ?>
       <div class="h3 text-center fw-bolder"> no user yet !!</div>
    <?php else :?>
      <?php if(array_key_exists('type',$_GET)): ?>
        <div class="alert alert-<?=$_GET['type']?>" role="alert">
             <?=$_GET['msg'] ?>
        </div>
    <?php endif;?>
<div class="container py-2 mt-3">
<div class="row text-center  gap-4">
  <div class="col-md-4">
<div class="float-end ">
     <form action="index.php" method="POST">
        <label>Show</label>
        <select name="record" onchange="this.form.submit()">
            <option value="10">10</option>
            <option value="5">5</option>
            <option value="2">2</option>
            <option value="100">100</option>
        </select>
        users
     </form>
  </div>
  </div>
  <div class="col-md-7">
  <form action="index.php" method="POST">
      <input type="search" name="search">
      <button class="btn btn-outline-success" name="btn_search">search</button>
     </form>
  </div>
</div>
<div class="d-flex justify-content-center">
<table class="table shadow rounded mt-5 w-50 p-5 table-striped">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Cin</th>
      <th scope="col">tlf</th>
      <th scope="col">operation</th>
    </tr>
  </thead>
  <tbody>
  <?php foreach($alluser as $value): ?>
    <tr>
      <td><?=$value['name'];?></td>
      <td><?=$value['email'];?></td>
      <td><?=$value['cin'];?></td>
      <td><?=$value['tlf'];?></td>
      <td>
        <a class="btn btn-outline-primary" href="../detailsuser?id=<?=$value['id'];?>"><i class="fa-solid fa-circle-info"></i></a>
        <a class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#exampleModal<?=$value['id'];?>" href="#"><i class="fa-solid fa-trash"></i></a>
        
        <div class="modal fade" id="exampleModal<?=$value['id'];?>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
           <div class="modal-dialog">
             <div class="modal-content">
               <div class="modal-header">
                 <h5 class="modal-title" id="exampleModalLabel">Delete User</h5>
                 <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
               </div>
               <div class="modal-body">
                 Are You Sure To Delete <?=$value['name'];?>
               </div>
               <div class="modal-footer">
                 <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                 <a class="btn btn-outline-danger" href="../deleteuser.php?id=<?=$value['id'];?>">Delete</a> 
               </div>
             </div>
           </div>
         </div>
         
      </td>
    </tr>
    <?php endforeach; ?>
  </tbody>
</table>

</div>
</div>
<nav class="d-flex justify-content-center" >
  <ul class="pagination">
    <li class="page-item ">
    <a class="page-link" href="index.php?page=<?=($previous)?>">previous</a>
    </li>
    <?php for($i=1;$i<=$pages;$i++): 
         if($i==$page){
            $active="active";
         }else{
          $active="";
         }?>
         
      <li class="page-item <?=$active?>"><a class="page-link" href="index.php?page=<?=$i?>"><?=$i?></a></li>
    <?php endfor;?>
    <li class="page-item">
      <a class="page-link" href="index.php?page=<?=$next?>">Next</a>
    </li>
  </ul>
</nav>
<?php endif;?>

