<div class="contianer d-flex justify-content-center py-4 mt-5">
<table class="table shadow mt-5 w-50 p-5 table-striped">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Cin</th>
      <th scope="col">tlf</th>
    </tr>
  </thead>
  <tbody>
    <tr>
     <?php foreach($alluser as $value): ?>
      <td><?=$value['name'];?></td>
      <td><?=$value['email'];?></td>
      <td><?=$value['cin'];?></td>
      <td><?=$value['tlf'];?></td>
    </tr>
    <?php endforeach; ?>
  </tbody>
</table>
</div>
