
<style>
img{
  height:100%;
  width:80%;
}

</style>
<div class="container-fluid">
<div class="d-flex justify-content-center py-3">
        <button class="text-center btn btn-outline-dark d-block"><a href="/Library_project"><i class="fa-solid text-warning fa-house-user display-4"></i></a> </button>
</div>

<div class="d-flex p-3 m-3 justify-content-center align-items-center">
    <div class="col-xl-10 col-md-12 col-lg-12">
        <div class="row here p-3 shadow-lg rounded">
                <div class="col-lg-6">
                        <div class="text-center">
                           <h1 class="h4 fw-bolder mb-3 py-3">Sign Up</h1>
                        </div>
                        <!--novalidate=""-->
                    <form class="py-4" action="index.php" method="POST"  enctype="multipart/form-data">
                     <?php if(array_key_exists('type',$_GET)): ?>   
                    <div class="alert alert-<?=$_GET['type']?>" role="alert">
                         <?=$_GET['msg'];?>
                      </div>
                    <?php endif; ?>
                       <div class="row mb-4 ">
                          <div class="col-lg-6">
                            <label>Name</label>
                            <input type="text" name="name" class="form-control " required>
                          </div>
                          <div class="col-lg-6">
                            <label>Email</label>
                            <input type="email" name="email" class="form-control ">
                          </div>
                        </div>
                        <div class="row mb-4">
                          <div class="col-lg-6 form-group">
                            <label>Cin</label>
                            <input type="Text" name="cin" class="form-control ">
                            <div class="invalid-feedback">
									            	What's your name?
									          </div>
                          </div>
                          <div class="col-lg-6">
                            <label>N° tlf</label>
                            <input type="text" name="tlf" class="form-control" pattern=[0-9]{8}>
                          </div>
                        </div>
                        <div class="row">
                          <div class="col-lg-6">
                            <label>Password</label>
                            <input type="password" name="password" class="form-control " required data-eye>
                          </div>
                          <div class="col-lg-6">
                            <label>Avatar</label>
                            <input type="file" name="avatar" class="form-control ">
                          </div>
                        </div>
                        <div class="form-group py-4">
									      	<input type="checkbox" name="agree" id="agree" class="custom-control-input" required>
										      <label for="agree" class="custom-control-label">I agree to the <a href="#">Terms and Conditions</a></label>
								       </div>
                        <div class="text-center mt-2">
                                <button name="signup" class="btn btn-outline-success">Sign Up</button>
                        </div>
                        <div class="mt-4 text-muted text-center">
									         Already have an account ? <a href="../login">Login</a>
								        </div>
                    </form>
                </div>
                <div class="col-lg-6 d-lg-block d-none text-center">
                        <img src="../images/signup.png" alt="">
                </div>
        </div>
    </div>
</div>
</div>
