<style>
 .reglage_card{
   transition-duration: 0.4s;
   cursor:pointer;
 }

 .reglage_card:hover{
    transform: scale(300px);
    box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2),0 6px 20px 0 rgba(0,0,0,0.19);
 }
</style>
<div class="row">
<?php foreach($books as $book) :?>  
<div class="col-lg-4 ">
<div class="card mb-3 reglage_card ">
  <div class="row g-0">
    <div class="col-md-5">
      <?php $newphoto=trim($book['avatar'] ,'.'); ?>
      <img src=".<?= $newphoto?>" width="100%"  class="img-fluid rounded-start" alt="photo book">
    </div>
    <div class="col-md-7">
        <div class="card-header bg-info fw-bolder text-white">
           <?=$book['name_book']?>
        </div>
        <div class="card-body">

             <table class="table table-danger rounded ">
                <thead>
                  <tr>
                    <td  class="fw-bolder">Author</td>
                    <td class="text-center fw-bolder">Nbr Despo</td>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td><?=$book['author_book']?></td>
                    <td class="text-center"><?=$book['nbr_book']?></td>
                  </tr>
                </tbody>
             </table>
             
             <div class="mt-2 mb-3">
               <h5 class="fw-bolder">Description :</h5>
                 <p class="text-muted"><?=$book['description_book']?></p> 
             </div>

             <div class="mt-2 mb-3">
               <h5 class="fw-bolder">Prix :</h5>
                 <p style="font-size:25px" class="text-warning"><?=$book['Prix']?> Dt</p> 
             </div>

             <div class="row py-3 mb-0">
                  <div class="col-md-6 mb-2">
                       <button class="btn btn-outline-danger text-dark" data-bs-toggle="modal" data-bs-target="#exampleModal<?=$book['idbook'];?>"><i class="fa-solid fa-trash"></i></button>
                  </div>
                  <div class="col-md-6">
                       <button class="btn btn-outline-warning"><a class="text-decoration-none  text-dark" href="../updatebook?id=<?=$book['idbook'];?>"> <i class="fa-solid fa-pen-to-square"></i> </a></button>
                  </div>
             </div>
        </div>
  </div>
 </div>
</div>
</div>
<?php endforeach;?>
</div>
