<style>
 .reglage_card{
   transition-duration: 0.4s;
   cursor:pointer;
 }

 .reglage_card:hover{
    transform: scale(300px);
    box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2),0 6px 20px 0 rgba(0,0,0,0.19);
 }
</style>

<div class="row gap-5 justify-content-center">
    <?php foreach($books as $book) :?>  
      <div  class="col-lg-3 py-2 ">
        <div class="card reglage_card text-center w-100">
          <?php $newphoto=trim($book['avatar'],'.')?>
            <img src=".<?=$newphoto;?>"  height="100px" class="card-img-top " alt="photo book">
             <div class="card-body">
              <div class="row">
                 <h5 class="card-title col-md-6">name   :<?=$book['name_book'];?></h5>
                 <h5 class="card-title col-md-6">author :<?=$book['author_book'];?></h5>
                 </div>
            <div class="row">
              <div class="col-md-6">  <p class="card-text"> Nombre dispo : <?=$book['nbr_book'];?></p></div>
              <div class="col-md-6">  Status :<span style="color:<?= $book['status']=='enable'? 'green' :''?>" ><?= $book['status'] ;?></span></div>
             </div>
                 decription : <p class="card-text"><?=$book['description_book'];?></p>
                 <?php for($i=0;$i<$book['rate'];$i++):?>
                     <i class="fa-solid fa-star text-warning"></i>
                  <?php endfor;?>
             </div>
    </div>
                 </div>
<?php endforeach;?>
 </div>
