

<h2 class="py-5 mt-2 text-center ">New book</h2>
<div class="d-flex justify-content-center">
<div class="row d-flex justify-content-center  gap-5 ">
   <?php foreach($books as $book): ?>
<div class="card mt-1" style="width: 18rem;">
  <img src="<?=$book['avatar']?>" class="card-img-top" alt="...">
  <div class="card-body">
    <p class="card-text">
        <div class="row text-center mb-4" >
         <div class="col-lg-6">
               <?=$book['name_book']?>
         </div>
         <div class="col-lg-6 text-center">
                <?=$book['author_book']?>
         </div>
        </div>
        <div class="row">
         <div class="col-lg-4">
            <form action="../likedbook.php" method="POST">
               <input  type="hidden" name="idbook" value=<?=$book['idbook']?>>
               <?php $verified=$admin->getalluser_liked($_SESSION['userid'],$book['idbook']); ?>
               <input  type="hidden" name="verified" value=<?=$verified['liked']?>>
               <?php $nombre=$admin->sommeliked($book['idbook']);?>
               <button type="submit" class="btn btn-light" name="like"><i class="<?= $verified['liked'] ?'fa-solid' : 'fa-regular'?> fa-thumbs-up px-1"></i><?=$nombre?></button>  
            </form>
         </div>
         <div class="col-lg-4 text-center">
         <form action="../favoritebook.php" method="POST">
               <input  type="hidden" name="idbook" value=<?=$book['idbook']?>>

               <?php $heart=$admin->getalluser_favorite($_SESSION['userid'],$book['idbook']); ?>
               <input  type="hidden" name="verified" value=<?=$heart['favorite']?>>
               <button type="submit" class="btn btn-light" name="favorite"><i class="<?= $heart['favorite'] ?'text-danger' : 'text-secondary'?> fa-solid fa-heart "></i></button>  
            </form>
         </div>
         <div class="col-lg-4 text-center">
            <?php $nombre=$carte->sommerate($book['idbook']);
                  $nbr=number_format($nombre,2,',','');?>
                <i class="fa-solid fa-star text-warning px-2"></i><?=$book['rate']?><?=$nbr?>
         </div>
        </div>
    </p>
  </div>
</div>
<?php endforeach;?>
</div>
</div>