

<h2 class="py-5 mt-2 text-center position-absolute">New book</h2>
<div class="d-flex justify-content-center">
<div class="row d-flex justify-content-center  mt-5 gap-5 py-5">
   <?php foreach($books as $book): ?>
<div class="card mt-4" style="width: 18rem;">
  <img src="<?=$book['avatar']?>" class="card-img-top" alt="...">
  <div class="card-body">
    <p class="card-text">
        <div class="row text-center mb-4" >
         <div class="col-lg-6">
               <?=$book['name_book']?>
         </div>
         <div class="col-lg-6 text-center">
                <?=$book['author_book']?>
         </div>
        </div>
        <div class="row">
         <div class="col-lg-4">
            <form action="../likedbook.php" method="POST">
               <input  type="hidden" name="idbook" value=<?=$book['idbook']?>>
               <button type="submit" class="btn btn-light" name="like"><i class="<?=$book['all_liked'] ?'fa-solid' : 'fa-regular'?> fa-thumbs-up px-1"></i><?=$book['all_liked']?></button>  
            </form>
         </div>
         <div class="col-lg-4 text-center">
         
                <i style="cursor:pointer" class="fa-solid fa-heart text-secondary"></i>
             <!--   <i style="cursor:pointer" class="fa-solid fa-heart text-danger"></i>-->
         </div>
         <div class="col-lg-4 text-center">
                <i class="fa-solid fa-star text-warning px-2"></i><?=$book['rate']?>
         </div>
        </div>
    </p>
  </div>
</div>
<?php endforeach;?>
</div>
</div>