
<style>
   
    body{
        background-color:#000;
    }
    .left_page{
         background-image: linear-gradient(to top,
             #70e1f5,#ffd194);
             height:90vh;
}
</style>
<div class="container-fluid  main">
    <div class="">
        <div class="row">
         <div class="col-lg-5 py-5  text-center left_page">
                 <h1 class="mb-5 text-secondary mx-0">Library Mejri</h1>
                 <p class="py-5 mt-5 text-white fw-bolder" style="font-size:50px;">You’re in! Get ready <br> for it.</p>
         </div>
         <div  class="col-lg-7 mt-5 py-5 text-white fw-bolder">
             <div class="py-5 mt-5 mx-5">
                <p style="font-size:25px;text-align:justify;"> Thanks for signing up—there's just one last thing to do.<br> Verify your email address by clicking the link <br> in your confirmation email.
                </p>
                <hr> 
                <div class=" text-muted">
                     <a href="/Library_project">Go Back Home. </a>  
                </div>
            </div>
         </div>
         </div>
    </div>
</div>
<footer>
     <div class="container-fluid py-2 bg-secondary">
        <div class="row text-center py-3">
           <div class="col-md-4 text-white">Copyright &copy; Library lbeez 2022</div>
           <div class="col-md-4">
              <a class="btn btn-warning text-white mx-2" href="#!" aria-label="Twitter"><i class="fab fa-twitter"></i></a>
              <a class="btn btn-warning text-white mx-2" href="#!" aria-label="Facebook"><i class="fab fa-facebook-f"></i></a>
              <a class="btn  btn-warning text-white mx-2" href="#!" aria-label="LinkedIn"><i class="fab fa-linkedin-in"></i></a>
           </div>
           <div class="col-md-4"> 
              <a class="text-white text-decoration-none me-3" href="#">Privacy Policy</a>
              <a class="text-white text-decoration-none" href="#">Terms of Use</a>
           </div>
        </div>
     </div>
</footer>