<div class="mt-5 text-center ">
       <button class="btn btn-outline-primary position-relative<?=empty($carte) ? 'disabled' : ''?>" data-bs-toggle="modal" data-bs-target="#exampleModal">
          <i class="text-dark fa-solid fa-cart-shopping"></i>
          <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
             <?=$carte->length_tab()?>
         </span>
        </button>
</div>
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Your Carte</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
          <?php foreach($carte->get_all_commande() as $items):?>
                  
                <div class="card">
                    <div class="card-header text-center">
                    </div>
                    <div class="card-body py-3">
                       <form action="index.php" method="Post"> 
                            <p class="h4 text-center"><?=$items[0]?></p>
                        <div class="text-center d-flex justify-content-center mb-3">
                        <p class="h4 text-center">Nombre Books <?=$items[1]?></p>
                        </div>
                        <div class="d-flex justify-content-center mb-3">
                          <button name="delete" class="btn btn-danger" value=<?=$items[0]?>>Delete</button>
                        </div>
                      </form>
                    </div>
                    <div> 
                    </div>
                  
                   
                  </div>   
                  <hr>
                  <?php endforeach;?>
                </div>
                <div class="modal-footer text-center">
                <form action="index.php" method="POST">
                  <?php if($carte->length_tab()>0): ?>
                             <div class="text-center d-flex justify-content-center mb-3">
                                      <div class="px-4"><input  class="from-control" type="radio" value="livraison" name="choisir" >livraison</div>
                                      <div class="px-4"><input  class="from-control" type="radio" value="sans livraison" name="choisir">sans livraison</div>
                             </div>
                  <?php endif; ?>
                 <button name="save" class="btn btn-outline-success <?=$carte->length_tab()==0? 'disabled' :''?>" >Save</button>
              </form>    
         <a name="reset" href="?reset" class="btn btn-outline-danger <?=$carte->length_tab()==0? 'disabled' :''?>">reset</a>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<div class="py-4 mt-5">
    <div  class="mx-5">
        <p class="mx-5 px-2" style="border-left:red 2px solid;font-size:25px">Books</p>
    </div>
    <div class="row mx-5">
        <div class="col-md-6 text-center mb-4">
            <form action="index.php" method="POST">
                <button class="btn btn-danger mb-2" name="all">all</button>
                <button class="btn btn-info  mb-2" name="action">action</button>
                <button class="btn btn-success  mb-2" name="adventure">adventure</button>
                <button class="btn btn-primary  mb-2" name="science">science</button>
            </form>
        </div>
        <div class="col-md-6 text-center">
             <form action="index.php" method="POST">
                    <input name="search" style="border:none;border-bottom:1px solid red;padding-left:15px;outline:none" placeholder="Search Your Book"  type="search">
                    <button class="btn btn-warning" name="btn_search">Search</button>
                </form> 
        </div>        
    </div>
<div class="d-flex justify-content-center">
    <?php if($trouve=0):?>
<div class="row d-flex justify-content-center  gap-5 ">
   <?php foreach($book_click as $book): ?>
<div class="card mt-1" style="width: 18rem">
  <img src="<?=$book['avatar']?>" class="card-img-top"  alt="...">
  <div class="card-body">
    <p class="card-text">
        <div class="row text-center mb-4" >
         <div class="col-lg-6">
               <?=$book['name_book']?>
         </div>
         <div class="col-lg-6 text-center">
                <?=$book['author_book']?>
         </div>
        </div>
        <div class="row">
         <div class="col-lg-4">
            <form action="../likedbook.php" method="POST">
               <input  type="hidden" name="idbook" value=<?=$book['idbook']?>>
               <input  type="hidden" name="liked" value=<?=$book['idbook']?>>
               <?php $verified=$admin->getalluser_liked($_SESSION['userid'],$book['idbook']); ?>
               <?php $nombre=$admin->sommeliked($book['idbook']);?>
               <button type="submit" class="btn btn-light" name="like"><i class="<?= $verified['liked'] ?'fa-solid' : 'fa-regular'?> fa-thumbs-up px-1"></i><?=$nombre?></button>  
            </form>
         </div>
         <div class="col-lg-4 text-center">
         <form action="../favoritebook.php" method="POST">
               <input  type="hidden" name="idbook" value=<?=$book['idbook']?>>
               <input  type="hidden" name="liked" value=<?=$book['idbook']?>>
               <?php $heart=$admin->getalluser_favorite($_SESSION['userid'],$book['idbook']); ?>
               <button type="submit" class="btn btn-light" name="favorite"><i class="<?= $heart['favorite'] ?'text-danger' : 'text-secondary'?> fa-solid fa-heart "></i></button>  
            </form>
         </div>
         <div class="col-lg-4 text-center">
           
                <i class="fa-solid fa-star text-warning px-2"></i><?=$book['rate']?>
         </div>
        </div>
    </p>
    
  </div>
</div>
<?php endforeach;?>
<?php else:?>
    <div class="row d-flex justify-content-center  gap-5 ">
   <?php foreach($book_click as $book): ?>
<div class="card mt-1" style="width: 18rem;">
  <img style="<?=$book['nbr_book']==0 ? 'filter:grayscale(1500)' :''?>" src="<?=$book['avatar']?>" class="card-img-top" alt="...">
  <div class="card-body">
    <p class="card-text">
        <div class="row text-center mb-4" >
         <div class="col-lg-6">
               <?=$book['name_book']?>
         </div>
         <div class="col-lg-6 text-center">
                <?=$book['author_book']?>
         </div>
        </div>
        <div class="row">
         <div class="col-lg-4">
            <form action="../likedbook.php" method="POST">
               <input  type="hidden" name="idbook" value=<?=$book['idbook']?>>
               <input  type="hidden" name="liked" value=<?=$book['idbook']?>>
               <?php $verified=$admin->getalluser_liked($_SESSION['userid'],$book['idbook']); ?>
               <?php $nombre=$admin->sommeliked($book['idbook']);?>
               <button type="submit" class="btn btn-light" name="like"><i class="<?= $verified['liked'] ?'fa-solid' : 'fa-regular'?> fa-thumbs-up px-1"></i><?=$nombre?></button>  
            </form>
         </div>
         <div class="col-lg-4 text-center">
         <form action="../favoritebook.php" method="POST">
               <input  type="hidden" name="idbook" value=<?=$book['idbook']?>>
               <input  type="hidden" name="liked" value=<?=$book['idbook']?>>
               <?php $heart=$admin->getalluser_favorite($_SESSION['userid'],$book['idbook']); ?>
               <button type="submit" class="btn btn-light" name="favorite"><i class="<?= $heart['favorite'] ?'text-danger' : 'text-secondary'?> fa-solid fa-heart "></i></button>  
            </form>
         </div>
         <div class="col-lg-4 text-center">
              <?php $somme=$carte->sommerate($book['idbook']); 
                   $nbr=number_format($somme,2,',',''); ?>
              <i class="fa-solid fa-star text-warning px-2"></i><?=$book['rate']?><?=$nbr?>
         </div>
        </div>
    </p>
    <div class="row py-2">
        <div class="col-md-6 text-center py-2">
           <p><?=$book['Prix']?> Dt</p> 
        </div>
        <div class="col-md-6 text-center">
            <form action="index.php" method="POST">
                     <input  type="hidden" name="idbook" value=<?=$book['idbook']?>>
                     <input class="form-control mb-3" type="number" name="quantity" placeholder="Nbr book" min="0" max=<?=$book['nbr_book']?>>
                     <button name="addcarte" class="btn btn-outline-dark text-warning<?= $book['nbr_book'] <= 0 ?  'disabled' : ''?>"> 
                       Add Cart<span class="badge"> <i class="text-warning fa-solid fa-cart-plus"></i></span>
                    </button>
                    
             </form>
        </div>
    </div>
  </div>
  <form action="index.php" method="POST">
  <div class="row mb-2">
     <input type="hidden" name="idbook" value=<?=$book['idbook']?>>
     <div class="col-md-6 text-center">
         <p class="<?=$book['nbr_book'] <= 0 ? 'text-danger' :'text-success'?>"> <?=$book['nbr_book'] <= 0 ? 'Out STock' : $book['nbr_book'] ?></p>
     </div>
     <div class="col-md-6 text-center">
       <button type="button" class="btn btn-outline-info" data-bs-toggle="modal" data-bs-target="#exampleModale<?=$book['idbook']?>">Add reviez</button>
      </div>
  </div>
  </form>
<!-- Modal -->
<div class="modal fade" id="exampleModale<?=$book['idbook']?>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"><?=$book['name_book']?></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      <?php if($carte->verfier_rate_user($_SESSION['userid'],$book['idbook'])==false): ?>
       <form action="index.php" method="POST"> 
          <label class="text-center">Add Your Rate</label>
          <input type="hidden" name="idbook" value=<?=$book['idbook']?>>
          <input type="number" class="form-control mb-2" name="nombre" min="1" max="5">
          <button name="rate"  class="btn btn-success">Save changes</button>
        </form>
        <?php endif; ?>
        <h2>List Of all Reviews :</h2>
          <?php foreach($carte->getallreviews($book['idbook']) as $review): ?>
              <div class="card p-2">
                <div class="row">
                  <div class="col-md-6">
                     <img class="rounded-pill shadow-sm" width="80px" src="<?=$review['avatar_admin']?>" alt="">
                  </div>
                  <div class="col-md-6">
                  <div class="card-text">Name :<?=$review['name']?></div>
                  <div class="card-body">
                    Rate :<?=$review['rate']?>
                  </div>
                  </div>
                  </div>
               </div>
          <?php endforeach; ?>
        </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
       
      </div>
    </div>
  </div>
</div>
</div>
<?php endforeach;?>
<?php endif;?>
</div>
</div>

