<div class="row mx-4 py-4">
    <h1>Demmande :</h1>
<?php foreach($commandes as $commande): ?>
    <?php if($commande['valider']==0): ?>  
    <div class="col-md-3 mb-3">
        <div style="background:whitesmoke" class="card">
             <div class="row p-2">
                    <div class="col-md-6 text-center">
                        <img  class="rounded-circle img-thumbnail shadow-sm" width='80px' src="<?=$commande['avatar_admin']?>" alt="">
                        <p class="mt-1 fw-bolder"><?=$commande['name']?></p>
                    </div>
                    <div class="col-md-6 text-center">
                        <img  class="rounded-circle img-thumbnail shadow-sm"  width='80px' src="<?=$commande['avatar']?>" alt="">
                        <p class="mt-1 fw-bolder"><?=$commande['name_book']?></p>
                    </div>
             </div>
             <table class="table">
                <thead class="bg-white">
                  <td>livraison</td>
                  <td>quantity</td>
                  <td>Prix</td>
                </thead>
                <tr>
                    <td><?=$commande['aveclivraison']?></td>
                    <td><?=$commande['quantity']?></td>
                    <td><?=$commande['Prix'] * $commande['quantity']?> Dt</td>
                </tr>
             </table>
             <form action="index.php" method="POST">
             <div class="row text-center mb-2">
                 <input type="hidden" name="idbook" value=<?=$commande['idbook']?>>
                 <input type="hidden" name="quantity" value=<?=$commande['quantity']?>>
                 <input type="hidden" name="iduser" value=<?=$commande['id']?>>
                 <input type="hidden" name="idcommande" value=<?=$commande['idcommande']?>>
                <div class="col-md-6">
                     <button name="valider" class="btn btn-outline-success">Accepter</button>
                </div>
                <div class="col-md-6">
                    <button name="rejeter" class="btn btn-outline-danger">Rejeter</button>
                </div>
             </div>
             </form>
        </div>
    </div>
<?php endif; ?>   
<?php endforeach; ?>
<div class="mt-5  rounded-pill ">
    <h1>Accepted</h1>
     <table class="table table-dark table-hover">
     <tr >
           <td>Name user</td>
           <td>Name Book</td>
           <td>Quantity</td>
           <td>livraison</td>
           <td>Date validation</td> 
           <td>Info</td>
       </tr>
       <?php foreach($commandes as $commande): ?>
        <?php if($commande['valider']==1): ?> 
            <tr>
           <td><?=$commande['name']?></td>
           <td><?=$commande['name_book']?></td>
           <td><?=$commande['quantity']?></td>
           <td><?=$commande['aveclivraison']?></td>
           <td><?= date("d/m/Y")?></td>
           <td><a class="btn btn-outline-primary" href="../detailsuser?id=<?=$commande['id']?>">Info</a></td>
       </tr>
       <?php endif; ?>
       <?php endforeach; ?>
    </table>
</div>
