<div class="row mx-4 py-4">
<h1>Demmande :</h1>
 <?php foreach($commandes as $commande): ?>
    
      <hr>
    <p class="fw-bolder text-center"> Commande N° <?=$commande['idcommande']?></p> 
    <?php if($commande['valider']==0): ?> 
         <?php foreach($book->all_line_commande_by_id($commande['idcommande']) as $line_commande): ?>
  <div class="col-md-3 mb-3 text-center">
        <div style="background:whitesmoke" class="card">
             <div class="row p-2">
                    <div class="col-md-6 text-center">
                        <img  class="rounded-circle img-thumbnail shadow-sm" width='80px' src="<?=$line_commande['avatar_admin']?>" alt="">
                        <p class="mt-1 fw-bolder"><?=$line_commande['name']?></p>
                    </div>
                    <div class="col-md-6 text-center">
                        <img  class="rounded-circle img-thumbnail shadow-sm"  width='80px' src="<?=$line_commande['avatar']?>" alt="">
                        <p class="mt-1 fw-bolder"><?=$line_commande['name_book']?></p>
                    </div>
             </div>
             <table class="table">
                <thead class="bg-white">
                  <td>livraison</td>
                  <td>quantity</td>
                  <td>Prix</td>
                </thead>
                <tr>
                    <td><?=$line_commande['aveclivraison']?></td>
                    <td><?=$line_commande['quantity']?></td>
                    <td><?=$line_commande['Prix'] * $line_commande['quantity']?> Dt</td>
                </tr>
             </table>

        </div>
    </div>
    
    <?php endforeach; ?>
    <form action="index.php" method="POST">
             <div class="row d-flew justify-content-center mb-2">
                 <input type="hidden" name="idbook" value=<?=$line_commande['idbook']?>>
                 <input type="hidden" name="quantity" value=<?=$line_commande['quantity']?>>
                 <input type="hidden" name="iduser" value=<?=$line_commande['id']?>>
                 <input type="hidden" name="idcommande" value=<?=$commande['idcommande']?>>
               
                 <div class="col-md-2">
                     <button name="valider" class="btn btn-outline-success">Accepter</button>
                </div>
                <div class="col-md-2">
                    <button name="rejeter" class="btn btn-outline-danger">Rejeter</button>
                </div>
                </div>
                </form>
                <hr>
<?php endif; ?>   

<?php endforeach; ?>


<div class="mt-5  rounded-pill ">
    <h1>Accepted</h1>
     <table class="table table-dark table-hover">
     <tr >
           <td>Name user</td>
           <td>Name Book</td>
           <td>Quantity</td>
           <td>livraison</td>
           <td>Date validation</td> 
           <td>Info</td>
       </tr>
       <?php foreach($commandes as $commande): ?>
        <?php if($commande['valider']==1): ?> 
            <tr>
           <td><?=$commande['name']?></td>
           <td><?=$commande['name_book']?></td>
           <td><?=$commande['quantity']?></td>
           <td><?=$commande['aveclivraison']?></td>
           <td><?=date("d/m/Y")?></td>
           <td><a class="btn btn-outline-primary" href="../detailsuser?id=<?=$commande['id']?>">Info</a></td>
       </tr>
       <?php endif; ?>
       <?php endforeach; ?>
    </table>
</div>
