<div class="h2 fw-bolder text-center mt-2"> Info user  </div>
<div class="container d-flex justify-content-center align-items-center py-3 mt-2">
<div class="card mb-3 mt-5" style="max-width: 540px; ">
  <div class="row ">
    <div class="col-md-4">
      <img src="<?=$getuser['avatar_admin'];?>" class="img-fluid rounded-start" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title"><?=$getuser['name'];?></h5>
        <p class="card-text"><?=$getuser['email'];?></p>
        <p class="card-text">Cin :<?=$getuser['cin'];?> </p>
        <p class="card-text">tlf :<?=$getuser['tlf'];?> </p>
        <p class="card-text"><small class="text-muted"></small></p>
      </div>
    </div>
  </div>
</div>
</div>