<style>
#hover:hover{
    background-color:whitesmoke;
}
.card-header{
    background:blue;
}
 .check{
    float: right;
}
.check img{
    width: 20px;
}
 .check span{
    color: #000;
    font-size: 12px;
    font-weight: 700px;
}
.footer{
    display: flex;
    justify-content: center;
    align-items: center;
    border-radius: 60px;
}
.chat{
    display: flex;
    flex-direction: column;
    height: 100vh;
    background: #f1f0e8;
}
 textarea{
    display: block;
    flex:1;
    width: 100%;
    border-radius: 60px;
    margin: 5px;
    height: 50px;
    outline: none;
    font-size: 19px;
    padding: 10px;
    padding-left: 40px;
    padding-right:90px ;
    border: 2px solid #ccc;
    color: #555;
    resize: none;
}
.addreact:active{
    background-color:red;
}
</style>
<div class="col-xl-10 py-5 container">
    <div class="row shadow-lg rounded">
        <div class="col-md-9 py-5 d-flex justify-content-center">
            <?php if(empty($user_choice)): ?>
                    <p class="mb-2 h2">Hello For Our Chats</p>
                    <div class="text-center">
                            <img src="../storage/emails, communication _ email, mail, surprise, letter, envelope, woman, people@2x.png" width="120px" alt="">
                    </div>
                    <?php else :?> 
                <!--style="position:fixed;z-index:0;width:29%"-->
            <div style="max-height:500px;overflow-y:auto;}" class="chat card mx-5 w-50">
                <div  class="card-header">
                    <div class="profil">
                  <img class="rounded-pill" width="50px" src="<?=$user_choice['avatar_admin']?>" alt="">
                  <span class="mx-4 fw-bolder text-white"><?=$user_choice['name']?></span>
                  </div>
                </div>
                <div  style="
                             background-attachment: fixed;
                             background-image: url(./bg.jpeg);
                             overflow-y: scroll;
                             padding-left: 20px;" 
                    class="card-body chat-box"
                >
                    <?php if(isset($_SESSION['userid'])){
                             $check_admin_user=$_SESSION['userid'];
                          }else if(isset($_SESSION['name'])){
                            $check_admin_user=$_SESSION['id'];
                          } ?>
              <?php foreach( $chat->getmessageofuser($check_admin_user,$user_choice['id']) as $message): ?>
               
                <?php if($message['idenvoi']==$check_admin_user):?>
               
                    <div class="float-end bg-primary p-2 rounded text-white fw-bolder">
                         <span class="text-center" style="word-break: break-all;"><?=$message['message']?></span>
                         <div class="check mt-4">
                               <span><?=$message['Date']?></span>      
                       </div>
                    </div>
                    <br>
                    <br>
                    <br>
                    <?php else:?>
                    <div>
                       <span>
                           <img class="rounded-pill me-2" width="30px" src="<?=$user_choice['avatar_admin']?>" alt="">
                        </span> 
                       <span class="bg-info p-2 rounded text-white fw-bolder">
                           <?=$message['message']?>
                           <div class="check">
                               <span><?=$message['Date']?></span>      
                       </div>
                      </span>
                    </div>
                    <br>
                    
                    <?php endif;?>
                   
                    <?php endforeach; ?>
                   
                </div>  
                <div>
                        <form action="index.php"  method="POST">
                        <div class="mt-2">
                            <div class="footer">
                                  <input type="hidden" name="id" value=<?=$user_choice['id']?>>
                                  <textarea name="message" width="20%" class="px-2" cols="10" rows="2" placeholder="Entrer votre message"></textarea>
                                  <button name="send" class="btn btn-success">Send</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <?php endif; ?>
        </div>
        <div style="border-left:1px solid #000 " class="col-md-2  py-2">
             <p class="fw-bolder text-primary text-center">All User</p>
             <form action="index.php" method="POST">
              <?php foreach($all_user as $user):?>
                  <?php if($user['role']==1):?>
                    <div>
                        <a style="text-decoration:none;color:#000" name="id" href="?id=<?=$user['id']?>">
                        <p>Admin:</p>
                         <p class="text-danger">
                            <div id="hover" style="cursor:pointer;" class="row">
                                <div class="col-md-4">
                                    <img src="<?=$user['avatar_admin']?>" class="rounded-pill shadow-sm" width="50px" alt="">
                                </div>
                                <div class="col-md-1 mt-2">
                                    <?=$user['name']?>
                                </div>
                            </div>
                         </p>
                         <hr>
                         </a>
                    </div>
                    <p>User:</p>
                    <?php else :?>
                         <a style="text-decoration:none;color:#000" name="id" href="?id=<?=$user['id']?>">
                            <div id="hover" style="cursor:pointer;" class="row hover-mask">
                                <div class="col-md-4 mask">
                                    <img src="<?=$user['avatar_admin']?>" class="rounded-pill shadow-sm" width="50px" alt="">
                                </div>
                                <div class="col-md-1 mt-2">
                                    <?=$user['name']?>
                                    <?php if($a== $user['id']):?>
                                          online
                                        <?php else :?>
                                            offline
                                            <?php endif;?>
                                </div>
                            </div>
                    </a>
                        <?php endif;?>
              <?php endforeach;?>
              </form>
        </div>
    </div>
</div>