<style>
#hover:hover{
    background-color:whitesmoke;}
</style>
<div class="col-xl-10 py-5 container">
    <div class="row shadow-lg rounded">
        <div class="col-md-9 py-5 d-flex justify-content-center">
            <?php if(empty($user_choice)): ?>
                    <p>Hello For Our Chats</p>
            <?php else :?> 
                <!--style="position:fixed;z-index:0;width:29%"-->
            <div style="max-height:500px;overflow-y:auto;}" class="card mx-5 w-50">
                <div  class=" card-header bg-secondary">
                  <img class="rounded-pill" width="50px" src="<?=$user_choice['avatar_admin']?>" alt="">
                  <span class="mx-4 fw-bolder text-white"><?=$user_choice['name']?></span>
                </div>
                <div class="card-body">
              <?php foreach( $chat->getmessageofuser($_SESSION['userid'],$user_choice['id']) as $message): ?>
                 <?php if($message['idenvoi']==$_SESSION['userid']):?>
                    <div class="float-end bg-primary p-2 rounded text-white fw-bolder">
                         <?=$message['message']?>
                    </div>
                    <br>
                    <br>
                    <?php else:?>
                    <div>
                       <span>
                           <img class="rounded-pill me-2" width="30px" src="<?=$user_choice['avatar_admin']?>" alt="">
                        </span> 
                       <span class="bg-info p-2 rounded text-white fw-bolder">
                           <?=$message['message']?>
                      </span>
                    </div>
                    <br>
                    <?php endif;?>
                    <?php endforeach; ?>
                    <div class="sticky mt-5">
                        <form action="index.php"  method="POST">
                        <div class="mt-2">
                            <div class="row">
                                <div class="col-md-10">
                                 <input type="hidden" name="id" value=<?=$user_choice['id']?>>
                                 <textarea name="message" width="20%" class="px-2 mt-5" cols="10" rows="2" placeholder="Entrer votre message"></textarea>
                                 </div> 
                                 <div class="col-md-2 mt-5">
                                  <button name="send" class="btn btn-success">Send</button>
                                 </div>
                            </div>
                        </div>
                        </form>
                    
                        </div>
                </div>  
            </div>
            <?php endif; ?>
        </div>
        <div style="border-left:1px solid #000 " class="col-md-2  py-2">
             <p class="fw-bolder text-primary text-center">All User</p>
             <form action="index.php" method="POST">
              <?php foreach($all_user as $user):?>
                  <?php if($user['role']==1):?>
                    <div>
                        <a style="text-decoration:none;color:#000" name="id" href="?id=<?=$user['id']?>">
                        <p>Admin:</p>
                         <p class="text-danger">
                            <div id="hover" style="cursor:pointer;" class="row">
                                <div class="col-md-4">
                                    <img src="<?=$user['avatar_admin']?>" class="rounded-pill shadow-sm" width="50px" alt="">
                                </div>
                                <div class="col-md-1 mt-2">
                                    <?=$user['name']?>
                                </div>
                            </div>
                         </p>
                         <hr>
                         </a>
                    </div>
                    <p>User:</p>
                    <?php else :?>
                         <a style="text-decoration:none;color:#000" name="id" href="?id=<?=$user['id']?>">
                            <div id="hover" style="cursor:pointer;" class="row hover-mask">
                                <div class="col-md-4 mask">
                                    <img src="<?=$user['avatar_admin']?>" class="rounded-pill shadow-sm" width="50px" alt="">
                                </div>
                                <div class="col-md-1 mt-2">
                                    <?=$user['name']?>
                                </div>
                            </div>
                    </a>
                        <?php endif;?>
              <?php endforeach;?>
              </form>
        </div>
    </div>
</div>