 
 <style>
   
.reglage_card{
   transition-duration: 0.4s;
   cursor:pointer;
 }

 .reglage_card:hover{
    transform: scale(150px);
    box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2),0 6px 20px 0 rgba(0,0,0,0.19);
 }
 
</style>
 
 <h1 class="text-center pt-3">List Of comments :</h1>
  <div class="d-flex justify-content-center mt-4">
     <form class="<?=empty($comments) ? 'd-none' :''?>" action="<?=$_SERVER['PHP_SELF'];?>" method="post">
         <input name="search" type="search" required  class="text-center form-control" placeholder="search comments">
         <br>
         <button name="save" class="btn btn-outline-warning">search</button>
      </div>
   </form>
<div class="row d-flex justify-content-center p-5">
    <?php if(empty($comments)):?>
         no comments
      <?php else:?>
   <?php if($trouve==1): ?>
 <?php foreach($comments as $com) :?>  
      
       <div class="card reglage_card">
         <div style="font-size:25px" class="card-header text-center fw-bolder">
          <a href="index.php?id=<?=$com['id']?>"><span><i name="close" class="fa-solid fa-xmark float-end text-danger"></i></span></a>      
           <?=$com['nom']?>
         </div>
        <div class="card-body mb-2">
                 <span style="font-size:20px" class="text-primary fw-bolder mb-2" >email: </span><?=$com['email'];?> 
                 <p style="font-size:20px" class="text-primary pt-2">Description :</p>
                  <?=$com['messages']?>
        </div>
     </div>
<?php endforeach;?>

</div>
<?php else :?>
 <?php foreach($comments as $com) :?>  
   <div class="col-lg-4 py-4 mx-5">
   <div class="card  reglage_card">
         <div style="font-size:25px" class="card-header text-center fw-bolder">
         <?=$com['nom']?> 
             <a href="index.php?id=<?=$com['id']?>"> <span><i name="close" class="fa-solid fa-xmark float-end text-danger"></i></span></a> 
         </div>
        <div class="card-body mb-2">
                <span style="font-size:20px" class="text-primary fw-bolder mb-2" >email: </span><?=$com['email'];?> 
                <p style="font-size:20px" class="text-primary pt-2">Description :</p>
                  <?=$com['messages']?>
        </div>
     </div>
</div>
<?php endforeach;?>
<?php endif ;?>
<?php endif;?>
</div>
</div>