<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
<div class="d-flex justify-content-center py-3"><script src="https://kit.fontawesome.com/c5bebe1cfa.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
     
<button class="text-center btn btn-outline-info d-block">
    <a href="/Library_project"><i class="fa-solid fa-house-user display-4"></i></a> </button>
</div>
 <div class="d-flex justify-content-center">
   <div class="card display-6">
        <div class="card-header">
            <?=$email ?>
        </div>
        <div class="card-body text-center text-danger fw-bolder">
            <?=$errors[0]?>
        </div>
        </div>
   </div>