<canvas style="position:absolute;width:70%" class="text-center" id="my-canvas"></canvas>
<div  class="content_overview">
<div class="row px-4  py-5">
     <div class="col-md-4 mb-4 ">
        <div class="card border-left-red shadow h-100 py-2">
                  <div class="card-body">
                         <div class="row align-items-center">
                               <div class="col mr-2">
                                   <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                            nombre of all the books</div>
                                   <div class="h5 mb-0 font-weight-bold text-gray-800"><?=$number_all_book?></div>
                                </div>
                                 <div class="col-auto">
                                       <i class="fa-solid fa-2x fa-book text-gray-300"></i>
                                  </div>
                            </div>
                     </div>
          </div>
     </div>

     <div class="col-md-4  mb-4 ">
        <div class="card border-left-primary shadow h-100 py-2">
                  <div class="card-body">
                         <div class="row no-gutters align-items-center">
                               <div class="col mr-2">
                                   <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                   nombre of Books enable</div>
                                   <div class="h5 mb-0 font-weight-bold "><?=$number_book_enable?></div>
                                </div>
                                 <div class="col-auto">
                                       <i class="fa-solid fa-2x  fa-book-bookmark"></i>
                                  </div>
                            </div>
                     </div>
          </div>
     </div>
  

     <div class="col-md-4 mb-4 ">
        <div class="card border-left-primary shadow h-100 py-2">
                  <div class="card-body">
                         <div class="row no-gutters align-items-center">
                               <div class="col mr-2">
                                   <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                   nombre of books issue</div>
                                   <div class="h5 mb-0 font-weight-bold text-gray-800"><?=$number_book_not_enable?></div>
                                </div>
                                 <div class="col-auto">
                                    <i class="fa-solid fa-2x fa-book-atlas"></i>
                                  </div>
                            </div>
                     </div>
          </div>
      </div>
    </div>
 <div class="row p-2 mx-5">
  <div class="col-md-4 py-5">
    <div class="card shadow mb-4 py-2">
        <div class="card-header">
            <h6 class="m-0 font-wieght-bold text-center text-shadow">Reveiw</h6>
        </div>
        <div class="card-body">
                <h4 class="small font-weight-bold">
                    books issue <span class="float-end"><?=$pourcentage_book_issue?>%</span>
                </h4>
                <div class="progress mb-2">
                    <div class="progress-bar bg-success" role="progressbar" style="width: <?=$pourcentage_book_issue?>%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                </div>

                <h4 class="small font-weight-bold">
                    books Enable <span class="float-end"><?=$pourcentage_book_enable?>%</span>
                </h4>
                <div class="progress">
                    <div class="progress-bar bg-danger" role="progressbar" style="width: <?=$pourcentage_book_enable?>%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
        </div>
    </div>
 </div>
 <div class="card w-50 h-50 mt-5 text-center col-md-4">
<?php if(empty($lastmessage)): ?>
       <p class="mt-2"> no comments</p>
    <?php else :?>

        <div class="card-header text-center">
            Last Commentaire
        </div>
         <div class="card-body text-center">
                  <p>Nom :<?=$lastmessage['nom'];?></p>
                  <p> email :<?=$lastmessage['email'];?></p>
                  <p> messsage : <?=$lastmessage['messages']?></p>
        </div>
    </div>
</div>
<?php endif;?>


</div>
  <script src="../js/index.min.js"></script>
<script>
   var confettiSettings = { target: 'my-canvas' };
   var confetti = new ConfettiGenerator(confettiSettings);
   confetti.render();
</script>