
<div class="py-5 mt-5 d-flex justify-content-center">
<form class="shadow-lg p-5 rounded" action="index.php"  method="POST">
    <!-- step 1 -->
    <?php if($suivant): ?>
    <div class="h4 text-center mb-5  text-primary display-5">Reset Password</div>
    <h4 class="mb-3">Entrer Votre  mail : </h4>
     <input class="form-control mb-2" type="email" name="email" placeholder="email@example.com" required>
     <h4 class="mb-3">Entrer Votre code envoi par mail : </h4>
     <input class="form-control mb-2" type="number" name="code" placeholder="****" required>
     <div class="text-center">
        <button name="confirmer" class="btn btn-outline-primary">confirmer</button>
    </div>
    <!-- step 2 -->
    <!-- change the password -->
    <?php else:?>
    <div class="h4 text-center mb-5  text-primary display-5">Changer Password</div>
      <h4 class="mb-3 text-center">****</h4>
      <label >New password</label>
     <input type="hidden" name="id" value="<?=$id?>">
     <input class="form-control mb-3" type="password" name="password" placeholder="******" required>
     <label >Confirm password</label>
     <input class="form-control mb-2" type="password" name="confirme" placeholder="******" required>
     <div class="text-center">
        <button name="update" class="btn btn-outline-primary">Changer</button>
    </div>
    <?php endif; ?>
</form>
</div>