<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
<div class="d-flex justify-content-center py-3"><script src="https://kit.fontawesome.com/c5bebe1cfa.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
     

<?php if($suivant==0): ?>
<div class="py-5 mt-5 d-flex justify-content-center ">
<form class="shadow-lg p-5 rounded " action="index.php" method="POST">
    <div class="h4 text-center mb-5  text-primary display-5">Reset Password</div>
     <input class="form-control mb-2" type="email" name="email" placeholder="Entrer Votre email" required>
     <div class="text-center">
        <button name="submit" class="btn btn-outline-success">Suivant</button>
    </div>
</form>
</div>
 <?php elseif($suivant==1): ?>

<div class="py-5 mt-5 d-flex justify-content-center">
     <!--   <form action="</?= $_SERVER['PHP_SELF'] ."?id=".$todo['id'] ?>" method="POST">-->
<form class="shadow-lg p-5 rounded " action="index.php?token=<?=$token_pass?>"  method="POST">
    <div class="h4 text-center mb-5  text-primary display-5">Reset Password</div>
      <h4 class="mb-3">Entrer Votre code envoi par mail : </h4>
     <input class="form-control mb-2" type="number" name="code" placeholder="****" required>
     <div class="text-center">
        <button name="confirmer" class="btn btn-outline-primary">confirmer</button>
    </div>
</form>
</div>
<?php endif;?>



